import { createContext, useContext, useMemo, useState } from 'react';

export const translations = {
    ru: {
        common: {
            noPhoto: 'Нет фото',
            loading: 'Загрузка...',
            close: 'Закрыть',
            cancel: 'Отменить',
            save: 'Сохранить',
            saving: 'Сохранение...',
            delete: 'Удалить',
            open: 'Открыть',
            call: 'Позвонить',
            yes: 'Да',
            no: 'Нет',
            notSpecified: 'Не указано',
            noDate: 'Нет даты',
            manualOrder: 'Ручной заказ',
            product: 'Товар',
            productId: 'ID товара',
            quantity: 'Количество',
            total: 'Итого',
            sum: 'Сумма',
            address: 'Адрес',
            client: 'Клиент',
            phone: 'Телефон',
            status: 'Статус',
            comment: 'Комментарий',
            itemsCount: 'шт.',
            moreItems: 'и еще {{count}}',
        },
        nav: {
            home: 'Главная',
            catalog: 'Каталог',
            customOrder: 'На заказ',
            contacts: 'Контакты',
            cart: 'Корзина',
            profile: 'Профиль',
            logout: 'Выйти',
            login: 'Вход',
            admin: 'Админ',
        },
        home: {
            heroTitle: 'Мебель',
            heroSubtitle: 'Со смыслом.',
            heroDesc: 'Исключительный дизайн, чистота форм и натуральные материалы. Создаем объекты, которые становятся частью вашей жизни.',
            heroCta: 'Смотреть коллекцию',
            featuredTitle: 'Избранное',
            featuredAll: 'Смотреть все',
            loading: 'Загрузка каталога...',
            noPhoto: 'Нет фото',
            ctaTitle: 'Готовы создать проект?',
            ctaDesc: 'Мы воплотим ваши идеи в реальность с безупречным вниманием к деталям.',
            ctaButton: 'Обсудить проект',
            heroAlt: 'Кухня Stolyarniy Dvor',
        },
        catalog: {
            title: 'Каталог',
            desc: 'Естественная фактура массива, чистые линии и ручной труд в каждой детали. Выберите предмет, который станет центром вашего пространства.',
            empty: 'Каталог пуст или обновляется.',
            noPhoto: 'Нет фото',
            details: 'Подробнее',
        },
        product: {
            backToCatalog: '← Вернуться в каталог',
            notFound: 'Товар не найден',
            philosophy: 'Философия изделия',
            woodText: 'Мы отбираем каждую доску вручную, чтобы сохранить ее природный рисунок. Массив дышит, живет и со временем обретает еще более глубокий характер. Каждый спил уникален, в этом истинная роскошь.',
            specs: [
                ['Размеры и конфигурация', 'Индивидуальные размеры под ваши задачи. Доступны разные варианты финишного покрытия.'],
                ['Материалы', 'Массив дуба, ясеня или ореха. Масло-воск европейского производства.'],
                ['Срок изготовления', 'От 14 до 30 рабочих дней в зависимости от сложности.'],
            ],
            orderButton: 'Заказать проект',
            addToCart: 'Добавить в корзину',
            addedToCart: '✓ Добавлено',
            relatedTitle: 'Похожие товары',
            previousPhoto: 'Предыдущее фото',
            nextPhoto: 'Следующее фото',
            heritageEyebrow: 'Наследие массива',
            heritageTitle: 'Вечная классика',
            relatedHeading: 'Дополните интерьер',
            relatedText: 'Безупречное сочетание предметов коллекции.',
            fullCatalog: 'Весь каталог',
            ctaTitle: 'Ощутите фактуру.',
            ctaText: 'Приходите в наш шоурум, чтобы прикоснуться к массиву лично. Или свяжитесь с нами для обсуждения индивидуального проекта.',
            contactsButton: 'Наши контакты',
            customOrderButton: 'Индивидуальный заказ',
            decreaseQuantity: 'Уменьшить количество',
            increaseQuantity: 'Увеличить количество',
        },
        cart: {
            title: 'Корзина',
            backToCatalog: 'Каталог',
            summary: 'Итого',
            total: 'Итого',
            emptyTitle: 'Корзина пуста',
            emptyDesc: 'Добавьте товары из каталога',
            goToCatalog: 'Перейти в каталог',
            noPhoto: 'Нет фото',
            orderData: 'Данные для заказа',
            name: 'Имя',
            phone: 'Телефон',
            address: 'Адрес доставки',
            comment: 'Комментарий',
            namePlaceholder: 'Ваше имя',
            addressPlaceholder: 'Город, улица, дом',
            commentPlaceholder: 'Пожелания к заказу',
            errName: 'Имя должно быть не короче 2 символов',
            errPhone: 'Введите корректный номер телефона',
            submitOrder: 'Оформить заказ',
            submitting: 'Оформление...',
            submitError: 'Не удалось оформить заказ. Попробуйте еще раз.',
            successTitle: 'Заказ оформлен!',
            successDesc: 'Мы свяжемся с вами в ближайшее время.',
            continueShopping: 'Продолжить покупки',
            goToCart: 'Перейти в корзину',
            unavailableWarning: 'Некоторые товары больше недоступны',
            removeUnavailable: 'Удалить',
            unavailableItem: 'Товар недоступен',
            removeItem: 'Удалить',
        },
        orderModal: {
            eyebrow: 'Оформление заказа',
            title: 'Проверьте данные и подтвердите заказ',
            product: 'Товар',
            selectProduct: 'Выберите товар',
            quantity: 'Количество',
            sum: 'Сумма',
            addProduct: '+ Добавить товар',
            totalAmount: 'Общая сумма',
            success: 'Заказ оформлен. Мы свяжемся с вами',
            autoClose: 'Окно закроется автоматически.',
            validationSummary: 'Проверьте обязательные поля: имя, телефон и адрес должны быть заполнены корректно.',
            name: 'Имя',
            namePlaceholder: 'Иван Иванов',
            nameHint: 'Укажите имя не короче 2 символов.',
            phone: 'Телефон',
            phoneHint: 'Номер нужен в формате +7XXXXXXXXXX.',
            address: 'Адрес доставки',
            addressPlaceholder: 'Город, улица, дом',
            addressHint: 'Добавьте полный адрес доставки, чтобы мы могли подтвердить заказ быстрее.',
            whatsapp: 'Связаться по WhatsApp',
            paymentMethod: 'Способ оплаты',
            cash: 'Наличными при получении',
            card: 'Перевод на карту',
            comment: 'Комментарий',
            commentPlaceholder: 'Уточнения к заказу, удобное время для связи и пожелания',
            cancel: 'Отмена',
            order: 'Заказать',
            ordered: 'Заказ оформлен',
            processing: 'Оформление...',
            close: 'Закрыть',
            errors: {
                name: 'Введите минимум 2 символа.',
                nameLetters: 'Допустимы только буквы и пробелы.',
                phone: 'Введите номер в формате +7XXXXXXXXXX.',
                address: 'Укажите адрес не короче 5 символов.',
                paymentMethod: 'Выберите способ оплаты.',
            },
        },
        customOrder: {
            title: 'Индивидуальный',
            subtitle: 'проект.',
            desc: 'От наброска до финального изделия. Опишите вашу идею, прикрепите референсы, и мы подготовим смету с учетом всех деталей.',
            customTitle: 'Индивидуальный заказ',
            steps: [
                { step: '01', title: 'Обсуждение', text: 'Выясняем сценарии использования, размеры и стилистику.' },
                { step: '02', title: 'Проектирование', text: 'Готовим детальный чертеж и точную смету изделия.' },
                { step: '03', title: 'Производство', text: 'Отбираем лучший массив и реализуем проект в дереве.' },
            ],
            stats: [
                { value: '5+', label: 'лет опыта' },
                { value: '200+', label: 'изделий' },
                { value: '100%', label: 'ручная работа' },
            ],
            formTitle: 'Запрос на расчет',
            labelName: 'Имя',
            labelPhone: 'Телефон',
            labelDetails: 'Детали проекта',
            labelRefs: 'Референсы (до 5 фото)',
            placeholderName: 'Ваше имя',
            placeholderPhone: '+7 (999) 000-00-00',
            placeholderDetails: 'Опишите, что вы хотите заказать...',
            uploadText: 'Нажмите или перетащите фото',
            uploadHint: 'PNG, JPG до 5 MB',
            submit: 'Отправить заявку',
            submitting: 'Отправка...',
            submitted: 'Отправлено ✓',
            successTitle: 'Заявка принята',
            successDesc: 'Мы свяжемся с вами в течение часа для обсуждения деталей.',
            errorAlert: 'Сбой при отправке заявки. Пожалуйста, попробуйте позже.',
        },
        contacts: {
            title: 'Связь.',
            desc: 'Мы всегда открыты к диалогу. Задайте вопрос, обсудите проект или приходите в наш шоурум, чтобы прикоснуться к массиву лично.',
            phone: 'Телефон',
            schedule: 'Пн-Вс: 09:00 - 19:00',
            whatsapp: 'WhatsApp',
            whatsappLink: 'Написать в WhatsApp',
            showroom: 'Шоурум',
            address: 'г. Астана, ул. Баршын 26',
            twoGis: 'Мы в 2ГИС',
            socials: 'Соцсети',
            writeUs: 'Написать нам',
            mapCaption: 'г. Астана, ул. Баршын 26',
            mapTitle: 'Шоурум на карте',
        },
        footer: {
            tagline: 'Столярная мастерская для серийного производства и индивидуальных заказов.',
            contacts: 'Контакты',
            socials: 'Соцсети',
            navigation: 'Навигация',
            cta: 'Обсудить проект',
            rights: '© 2026 Stolyarniy Dvor • Все права защищены',
        },
        auth: {
            tagline: 'Мебель с характером и качеством',
            login: 'Вход',
            register: 'Регистрация',
            namePlaceholder: 'Ваше имя',
            phonePlaceholder: 'Телефон (+7...)',
            passwordPlaceholder: 'Пароль',
            confirmPasswordPlaceholder: 'Подтверждение пароля',
            loading: 'Загрузка...',
            loginButton: 'Войти',
            registerButton: 'Зарегистрироваться',
            passwordMismatch: 'Пароли не совпадают',
            connectionError: 'Нет соединения с сервером',
        },
        profile: {
            defaultOrderName: 'Заказ',
            productNumber: 'Товар #{{id}}',
            ordersLoadError: 'Ошибка загрузки заказов:',
            editProfile: 'Редактировать профиль',
            myOrders: 'Мои заказы',
            noOrdersTitle: 'У вас пока нет заказов',
            noOrdersDesc: 'Вы еще ничего не заказывали. Перейдите в каталог, чтобы сделать свой первый заказ и обновить интерьер.',
            goToCatalog: 'Перейти в каталог',
            orderTitle: 'Заказ #{{id}}',
            moreItems: 'и еще {{count}}',
            details: 'Подробнее',
            repeat: 'Повторить',
            orderDetails: 'Детали заказа #{{id}}',
            goods: 'Товары',
            status: 'Статус',
            createdAt: 'Дата оформления',
            amount: 'Сумма',
            profileUpdated: 'Профиль обновлен',
            dataSaved: 'Данные успешно сохранены',
            editTitle: 'Редактировать профиль',
            name: 'Имя *',
            phone: 'Телефон *',
            leavePasswordEmpty: 'Оставьте пустым, чтобы не менять пароль',
            newPassword: 'Новый пароль',
            minPasswordPlaceholder: 'Минимум 6 символов',
            confirmPassword: 'Подтвердите пароль',
            repeatPasswordPlaceholder: 'Повторите пароль',
            save: 'Сохранить',
            saving: 'Сохранение...',
            loginRequired: 'Пожалуйста, войдите в систему.',
            serverError: 'Ошибка сервера',
            errors: {
                name: 'Имя должно быть не короче 2 символов',
                phone: 'Введите корректный номер телефона',
                password: 'Минимум 6 символов',
                confirmPassword: 'Пароли не совпадают',
            },
        },
        statuses: {
            NEW: 'Новый',
            IN_PROGRESS: 'В работе',
            PROCESS: 'В работе',
            READY: 'Готов',
            DONE: 'Выполнен',
            CANCELLED: 'Отменен',
        },
        admin: {
            dashboard: {
                title: 'Панель Управления',
                loading: 'Загрузка данных...',
                downloadReport: 'Скачать отчет',
                allProducts: 'Всех товаров',
                ordersForPeriod: 'Заказов за период',
                newOrders: 'Новых заказов',
                forPeriod: 'за период',
                noPreviousData: 'нет данных прошлого периода',
                revenue: 'Общая выручка',
                avgCheck: 'Средний чек',
                totalNew: 'Всего новых',
                chartTitle: 'Динамика заказов',
                byMonths: 'по месяцам',
                byDays: 'по дням',
                notes: 'Заметки',
                notesPlaceholder: 'Запишите идеи, номера или дела на сегодня...',
                saveNotes: 'Сохранить заметки',
                notesSaved: 'Заметки сохранены',
                recentOrders: 'Последние заказы',
                noOrders: 'Пока нет заказов.',
                productFallback: 'Товар #{{id}}',
                reportTitle: 'ОТЧЕТ ПО ЗАКАЗАМ',
                reportPeriod: 'Период: {{period}}',
                reportDate: 'Дата формирования: {{date}}',
                sheetOrders: 'Заказы',
                sheetSummary: 'Сводка',
                sheetByDays: 'По дням',
                tableHeaders: ['ID', 'Дата', 'Клиент', 'Телефон', 'Адрес', 'Товары', 'Кол-во товаров', 'Сумма (₸)', 'Статус'],
                summaryTitle: 'СВОДКА',
                summaryMetric: 'Показатель',
                summaryValue: 'Значение',
                summaryOrders: 'Общее количество заказов',
                summaryRevenue: 'Общая выручка (₸)',
                summaryAvg: 'Средний чек (₸)',
                summaryPopular: 'Самый популярный товар',
                summaryNewOrders: 'Кол-во новых заказов',
                pieces: 'шт.',
                byDaysTitle: 'ПО ДНЯМ',
                date: 'Дата',
                ordersCount: 'Кол-во заказов',
                fileName: 'Отчет_заказов',
                period: 'Период',
                today: 'Сегодня',
                sevenDays: '7 дней',
                thirtyDays: '30 дней',
                thisMonth: 'Этот месяц',
                clickEndDate: 'Кликните на конечную дату',
            },
            tabs: {
                home: 'Главная',
                orders: 'Заказы',
                products: 'Товары',
            },
            products: {
                title: 'Админка',
                addProduct: 'Добавить товар',
                namePlaceholder: 'Название',
                pricePlaceholder: 'Цена',
                descriptionPlaceholder: 'Описание',
                uploadImage: 'Загрузить изображение',
                uploadLoading: 'Загрузка...',
                maxImages: 'Максимум 5 изображений',
                uploadError: 'Ошибка загрузки',
                loadError: 'Ошибка загрузки товаров',
                addError: 'Ошибка добавления',
                deleteConfirm: 'Удалить товар?',
                deleteError: 'Ошибка удаления',
                adding: 'Добавление...',
                add: 'Добавить',
            },
            orders: {
                loadError: 'Ошибка загрузки данных.',
                statusUpdateError: 'Ошибка обновления статуса заказа',
                commentSaveError: 'Ошибка сохранения комментария администратора',
                createError: 'Ошибка создания заказа',
                title: 'Панель Управления',
                manualCreate: 'Создать заказ вручную',
                openFormHint: 'Нажмите, чтобы открыть форму',
                products: 'Товары',
                addProduct: '+ Добавить товар',
                product: 'Товар',
                selectProduct: 'Выберите товар',
                quantity: 'Количество',
                total: 'Итого',
                clientName: 'Имя клиента',
                namePlaceholder: 'Введите имя',
                phone: 'Телефон',
                address: 'Адрес доставки',
                addressPlaceholder: 'Город, улица, дом',
                whatsapp: 'Связаться через WhatsApp',
                paymentMethod: 'Способ оплаты',
                cash: 'Наличными при получении',
                card: 'Перевод на карту',
                comment: 'Комментарий',
                commentPlaceholder: 'Дополнительная информация, пожелания клиента или детали',
                options: 'Варианты / Опции',
                optionsPlaceholder: 'JSON или текст, например: {"size":"160x80","color":"oak"}',
                creating: 'Создание...',
                createOrder: 'Создать заказ',
                customerOrders: 'Заказы клиентов',
                listHint: 'Быстрый поиск по клиенту и статусу, без перезагрузки списка.',
                searchPlaceholder: 'Поиск по имени или телефону',
                noStatuses: 'Статусы не выбраны',
                statusesPrefix: 'Статусы: {{statuses}}',
                filter: 'Фильтр',
                statuses: 'Статусы',
                reset: 'Сбросить',
                loading: 'Загрузка заказов...',
                empty: 'Заказов пока нет.',
                noProducts: 'Нет товаров',
                productId: 'ID товара: {{id}}',
                payment: 'Оплата',
                open: 'Открыть',
                call: 'Позвонить',
                cancel: 'Отменить',
                modalTitle: 'Заказ #{{id}}',
                goodsWithCount: 'Товары ({{count}} шт.)',
                totalAmount: 'Общая сумма',
                createdAt: 'Дата создания',
                updatedAt: 'Дата обновления',
                source: 'Источник',
                customerComment: 'Комментарий клиента',
                adminComment: 'Комментарий администратора',
                adminCommentPlaceholder: 'Внутренний комментарий для команды',
                referenceImages: 'Изображения референсов',
                uploadedByUser: 'Загружено пользователем',
                saveComment: 'Сохранить комментарий',
                done: 'Готово',
                noPhone: 'Нет телефона',
            },
        },
    },
    kz: {
        common: {
            noPhoto: 'Фото жоқ',
            loading: 'Жүктелуде...',
            close: 'Жабу',
            cancel: 'Болдырмау',
            save: 'Сақтау',
            saving: 'Сақталуда...',
            delete: 'Жою',
            open: 'Ашу',
            call: 'Қоңырау шалу',
            yes: 'Иә',
            no: 'Жоқ',
            notSpecified: 'Көрсетілмеген',
            noDate: 'Күні жоқ',
            manualOrder: 'Қолмен жасалған тапсырыс',
            product: 'Тауар',
            productId: 'Тауар ID',
            quantity: 'Саны',
            total: 'Жиыны',
            sum: 'Сома',
            address: 'Мекенжай',
            client: 'Клиент',
            phone: 'Телефон',
            status: 'Статус',
            comment: 'Пікір',
            itemsCount: 'дана',
            moreItems: 'тағы {{count}}',
        },
        nav: {
            home: 'Басты',
            catalog: 'Каталог',
            customOrder: 'Тапсырыс',
            contacts: 'Байланыс',
            cart: 'Себет',
            profile: 'Профиль',
            logout: 'Шығу',
            login: 'Кіру',
            admin: 'Әкімші',
        },
        home: {
            heroTitle: 'Жиһаз',
            heroSubtitle: 'Мағынамен.',
            heroDesc: 'Таңдаулы дизайн, таза пішін және табиғи материалдар. Өміріңіздің бір бөлігіне айналатын заттар жасаймыз.',
            heroCta: 'Коллекцияны көру',
            featuredTitle: 'Таңдаулылар',
            featuredAll: 'Барлығын көру',
            loading: 'Каталог жүктелуде...',
            noPhoto: 'Фото жоқ',
            ctaTitle: 'Жоба жасауға дайынсыз ба?',
            ctaDesc: 'Идеяларыңызды шындыққа айналдырамыз, ең кіші бөлшекке дейін.',
            ctaButton: 'Жобаны талқылау',
            heroAlt: 'Stolyarniy Dvor асүйі',
        },
        catalog: {
            title: 'Каталог',
            desc: 'Массивтің табиғи текстурасы, таза сызықтар және қол еңбегі. Кеңістігіңіздің орталығына айналатын затты таңдаңыз.',
            empty: 'Каталог бос немесе жаңартылуда.',
            noPhoto: 'Фото жоқ',
            details: 'Толығырақ',
        },
        product: {
            backToCatalog: '← Каталогқа оралу',
            notFound: 'Тауар табылмады',
            philosophy: 'Бұйымның философиясы',
            woodText: 'Табиғи өрнегін сақтау үшін әр тақтаны қолмен іріктейміз. Массив дем алады, өмір сүреді және уақыт өте тереңдей түседі. Әр кесінді бірегей, шынайы сән осында.',
            specs: [
                ['Өлшемдер мен конфигурация', 'Міндеттеріңізге сай жеке өлшемдер. Әр түрлі әрлеу нұсқалары қолжетімді.'],
                ['Материалдар', 'Емен, шаған немесе жаңғақ массиві. Еуропалық май-балауыз.'],
                ['Дайындау мерзімі', 'Күрделілігіне байланысты 14-тен 30 жұмыс күніне дейін.'],
            ],
            orderButton: 'Жобаға тапсырыс беру',
            addToCart: 'Себетке қосу',
            addedToCart: '✓ Қосылды',
            relatedTitle: 'Ұқсас тауарлар',
            previousPhoto: 'Алдыңғы фото',
            nextPhoto: 'Келесі фото',
            heritageEyebrow: 'Массив мұрасы',
            heritageTitle: 'Мәңгілік классика',
            relatedHeading: 'Интерьерді толықтырыңыз',
            relatedText: 'Коллекция заттарының мінсіз үйлесімі.',
            fullCatalog: 'Толық каталог',
            ctaTitle: 'Фактураны сезініңіз.',
            ctaText: 'Массивті қолмен сезіну үшін шоурумға келіңіз. Немесе жеке жобаны талқылау үшін бізбен байланысыңыз.',
            contactsButton: 'Байланыстар',
            customOrderButton: 'Жеке тапсырыс',
            decreaseQuantity: 'Санын азайту',
            increaseQuantity: 'Санын көбейту',
        },
        cart: {
            title: 'Себет',
            backToCatalog: 'Каталог',
            summary: 'Жиыны',
            total: 'Жиыны',
            emptyTitle: 'Себет бос',
            emptyDesc: 'Каталогтан тауарлар қосыңыз',
            goToCatalog: 'Каталогқа өту',
            noPhoto: 'Фото жоқ',
            orderData: 'Тапсырыс деректері',
            name: 'Аты',
            phone: 'Телефон',
            address: 'Жеткізу мекенжайы',
            comment: 'Пікір',
            namePlaceholder: 'Атыңыз',
            addressPlaceholder: 'Қала, көше, үй',
            commentPlaceholder: 'Тапсырысқа тілектер',
            errName: 'Атыңыз 2 таңбадан кем болмауы керек',
            errPhone: 'Дұрыс телефон нөмірін енгізіңіз',
            submitOrder: 'Тапсырыс беру',
            submitting: 'Рәсімделуде...',
            submitError: 'Тапсырысты рәсімдеу мүмкін болмады. Қайталап көріңіз.',
            successTitle: 'Тапсырыс рәсімделді!',
            successDesc: 'Жақын арада сізбен байланысамыз.',
            continueShopping: 'Сатып алуды жалғастыру',
            goToCart: 'Себетке өту',
            unavailableWarning: 'Кейбір тауарлар қолжетімді емес',
            removeUnavailable: 'Жою',
            unavailableItem: 'Тауар қолжетімді емес',
            removeItem: 'Жою',
        },
        orderModal: {
            eyebrow: 'Тапсырысты рәсімдеу',
            title: 'Деректерді тексеріп, тапсырысты растаңыз',
            product: 'Тауар',
            selectProduct: 'Тауарды таңдаңыз',
            quantity: 'Саны',
            sum: 'Сома',
            addProduct: '+ Тауар қосу',
            totalAmount: 'Жалпы сома',
            success: 'Тапсырыс рәсімделді. Біз сізбен байланысамыз',
            autoClose: 'Терезе автоматты түрде жабылады.',
            validationSummary: 'Міндетті өрістерді тексеріңіз: аты, телефон және мекенжай дұрыс толтырылуы керек.',
            name: 'Аты',
            namePlaceholder: 'Атыңыз',
            nameHint: 'Атыңыз кемінде 2 таңба болсын.',
            phone: 'Телефон',
            phoneHint: 'Нөмір +7XXXXXXXXXX форматында болуы керек.',
            address: 'Жеткізу мекенжайы',
            addressPlaceholder: 'Қала, көше, үй',
            addressHint: 'Тапсырысты тезірек растау үшін толық мекенжайды қосыңыз.',
            whatsapp: 'WhatsApp арқылы байланысу',
            paymentMethod: 'Төлем тәсілі',
            cash: 'Алғанда қолма-қол',
            card: 'Картаға аудару',
            comment: 'Пікір',
            commentPlaceholder: 'Тапсырысқа нақтылау, байланысуға ыңғайлы уақыт және тілектер',
            cancel: 'Болдырмау',
            order: 'Тапсырыс беру',
            ordered: 'Тапсырыс рәсімделді',
            processing: 'Рәсімделуде...',
            close: 'Жабу',
            errors: {
                name: 'Кемінде 2 таңба енгізіңіз.',
                nameLetters: 'Тек әріптер мен бос орындар рұқсат.',
                phone: '+7XXXXXXXXXX форматындағы нөмірді енгізіңіз.',
                address: 'Мекенжай кемінде 5 таңба болуы керек.',
                paymentMethod: 'Төлем тәсілін таңдаңыз.',
            },
        },
        customOrder: {
            title: 'Жеке',
            subtitle: 'жоба.',
            desc: 'Эскизден дайын бұйымға дейін. Идеяңызды сипаттаңыз, референстерді тіркеңіз, біз барлық бөлшектерді ескеріп смета дайындаймыз.',
            customTitle: 'Жеке тапсырыс',
            steps: [
                { step: '01', title: 'Талқылау', text: 'Пайдалану сценарийлерін, өлшемдер мен стилистиканы анықтаймыз.' },
                { step: '02', title: 'Жобалау', text: 'Егжей-тегжейлі сызба және нақты смета дайындаймыз.' },
                { step: '03', title: 'Өндіріс', text: 'Ең жақсы массивті іріктеп, жобаны ағашта жүзеге асырамыз.' },
            ],
            stats: [
                { value: '5+', label: 'жыл тәжірибе' },
                { value: '200+', label: 'бұйым' },
                { value: '100%', label: 'қол жұмысы' },
            ],
            formTitle: 'Есеп сұрауы',
            labelName: 'Аты',
            labelPhone: 'Телефон',
            labelDetails: 'Жоба мәліметтері',
            labelRefs: 'Референстер (5 фотоға дейін)',
            placeholderName: 'Атыңыз',
            placeholderPhone: '+7 (999) 000-00-00',
            placeholderDetails: 'Не тапсырыс бергіңіз келетінін сипаттаңыз...',
            uploadText: 'Басыңыз немесе фотоны сүйреңіз',
            uploadHint: 'PNG, JPG 5 MB дейін',
            submit: 'Өтінімді жіберу',
            submitting: 'Жіберілуде...',
            submitted: 'Жіберілді ✓',
            successTitle: 'Өтінім қабылданды',
            successDesc: 'Бір сағат ішінде бөлшектерді талқылау үшін хабарласамыз.',
            errorAlert: 'Өтінімді жіберу сәтсіз аяқталды. Кейінірек қайталап көріңіз.',
        },
        contacts: {
            title: 'Байланыс.',
            desc: 'Біз әрдайым диалогқа ашықпыз. Сұрақ қойыңыз, жобаны талқылаңыз немесе массивті жеке ұстап көру үшін шоурумға келіңіз.',
            phone: 'Телефон',
            schedule: 'Дс-Жс: 09:00 - 19:00',
            whatsapp: 'WhatsApp',
            whatsappLink: 'WhatsApp-қа жазу',
            showroom: 'Шоурум',
            address: 'Астана қ., Баршын көш. 26',
            twoGis: '2ГИС-те ашу',
            socials: 'Әлеуметтік желілер',
            writeUs: 'Бізге жазу',
            mapCaption: 'Астана қ., Баршын көш. 26',
            mapTitle: 'Шоурум картада',
        },
        footer: {
            tagline: 'Сериялы өндіріс пен жеке тапсырыстарға арналған ағаш шеберханасы.',
            contacts: 'Байланыс',
            socials: 'Әлеуметтік желілер',
            navigation: 'Навигация',
            cta: 'Жобаны талқылау',
            rights: '© 2026 Stolyarniy Dvor • Барлық құқықтар қорғалған',
        },
        auth: {
            tagline: 'Мінезі мен сапасы бар жиһаз',
            login: 'Кіру',
            register: 'Тіркелу',
            namePlaceholder: 'Атыңыз',
            phonePlaceholder: 'Телефон (+7...)',
            passwordPlaceholder: 'Құпиясөз',
            confirmPasswordPlaceholder: 'Құпиясөзді растау',
            loading: 'Жүктелуде...',
            loginButton: 'Кіру',
            registerButton: 'Тіркелу',
            passwordMismatch: 'Құпиясөздер сәйкес емес',
            connectionError: 'Сервермен байланыс жоқ',
        },
        profile: {
            defaultOrderName: 'Тапсырыс',
            productNumber: 'Тауар #{{id}}',
            ordersLoadError: 'Тапсырыстарды жүктеу қатесі:',
            editProfile: 'Профильді өзгерту',
            myOrders: 'Менің тапсырыстарым',
            noOrdersTitle: 'Сізде әзірге тапсырыс жоқ',
            noOrdersDesc: 'Сіз әлі ештеңе тапсырыс берген жоқсыз. Бірінші тапсырысты жасау үшін каталогқа өтіңіз.',
            goToCatalog: 'Каталогқа өту',
            orderTitle: 'Тапсырыс #{{id}}',
            moreItems: 'тағы {{count}}',
            details: 'Толығырақ',
            repeat: 'Қайталау',
            orderDetails: 'Тапсырыс мәліметтері #{{id}}',
            goods: 'Тауарлар',
            status: 'Статус',
            createdAt: 'Рәсімделген күні',
            amount: 'Сома',
            profileUpdated: 'Профиль жаңартылды',
            dataSaved: 'Деректер сәтті сақталды',
            editTitle: 'Профильді өзгерту',
            name: 'Аты *',
            phone: 'Телефон *',
            leavePasswordEmpty: 'Құпиясөзді өзгертпеу үшін бос қалдырыңыз',
            newPassword: 'Жаңа құпиясөз',
            minPasswordPlaceholder: 'Кемінде 6 таңба',
            confirmPassword: 'Құпиясөзді растаңыз',
            repeatPasswordPlaceholder: 'Құпиясөзді қайталаңыз',
            save: 'Сақтау',
            saving: 'Сақталуда...',
            loginRequired: 'Жүйеге кіріңіз.',
            serverError: 'Сервер қатесі',
            errors: {
                name: 'Атыңыз 2 таңбадан кем болмауы керек',
                phone: 'Дұрыс телефон нөмірін енгізіңіз',
                password: 'Кемінде 6 таңба',
                confirmPassword: 'Құпиясөздер сәйкес емес',
            },
        },
        statuses: {
            NEW: 'Жаңа',
            IN_PROGRESS: 'Жұмыста',
            PROCESS: 'Жұмыста',
            READY: 'Дайын',
            DONE: 'Орындалды',
            CANCELLED: 'Болдырылмады',
        },
        admin: {
            dashboard: {
                title: 'Басқару панелі',
                loading: 'Деректер жүктелуде...',
                downloadReport: 'Есепті жүктеу',
                allProducts: 'Барлық тауарлар',
                ordersForPeriod: 'Кезеңдегі тапсырыстар',
                newOrders: 'Жаңа тапсырыстар',
                forPeriod: 'кезең бойынша',
                noPreviousData: 'өткен кезең деректері жоқ',
                revenue: 'Жалпы түсім',
                avgCheck: 'Орташа чек',
                totalNew: 'Барлық жаңалар',
                chartTitle: 'Тапсырыстар динамикасы',
                byMonths: 'айлар бойынша',
                byDays: 'күндер бойынша',
                notes: 'Жазбалар',
                notesPlaceholder: 'Бүгінгі идеялар, нөмірлер немесе істерді жазыңыз...',
                saveNotes: 'Жазбаларды сақтау',
                notesSaved: 'Жазбалар сақталды',
                recentOrders: 'Соңғы тапсырыстар',
                noOrders: 'Әзірге тапсырыс жоқ.',
                productFallback: 'Тауар #{{id}}',
                reportTitle: 'ТАПСЫРЫСТАР ЕСЕБІ',
                reportPeriod: 'Кезең: {{period}}',
                reportDate: 'Құрылған күні: {{date}}',
                sheetOrders: 'Тапсырыстар',
                sheetSummary: 'Жиынтық',
                sheetByDays: 'Күндер бойынша',
                tableHeaders: ['ID', 'Күні', 'Клиент', 'Телефон', 'Мекенжай', 'Тауарлар', 'Тауар саны', 'Сома (₸)', 'Статус'],
                summaryTitle: 'ЖИЫНТЫҚ',
                summaryMetric: 'Көрсеткіш',
                summaryValue: 'Мәні',
                summaryOrders: 'Тапсырыстардың жалпы саны',
                summaryRevenue: 'Жалпы түсім (₸)',
                summaryAvg: 'Орташа чек (₸)',
                summaryPopular: 'Ең танымал тауар',
                summaryNewOrders: 'Жаңа тапсырыстар саны',
                pieces: 'дана',
                byDaysTitle: 'КҮНДЕР БОЙЫНША',
                date: 'Күні',
                ordersCount: 'Тапсырыс саны',
                fileName: 'Тапсырыстар_есебі',
                period: 'Кезең',
                today: 'Бүгін',
                sevenDays: '7 күн',
                thirtyDays: '30 күн',
                thisMonth: 'Осы ай',
                clickEndDate: 'Соңғы күнді басыңыз',
            },
            tabs: {
                home: 'Басты',
                orders: 'Тапсырыстар',
                products: 'Тауарлар',
            },
            products: {
                title: 'Әкімші',
                addProduct: 'Тауар қосу',
                namePlaceholder: 'Атауы',
                pricePlaceholder: 'Бағасы',
                descriptionPlaceholder: 'Сипаттама',
                uploadImage: 'Сурет жүктеу',
                uploadLoading: 'Жүктелуде...',
                maxImages: 'Ең көбі 5 сурет',
                uploadError: 'Жүктеу қатесі',
                loadError: 'Тауарларды жүктеу қатесі',
                addError: 'Қосу қатесі',
                deleteConfirm: 'Тауарды жою керек пе?',
                deleteError: 'Жою қатесі',
                adding: 'Қосылуда...',
                add: 'Қосу',
            },
            orders: {
                loadError: 'Деректерді жүктеу қатесі.',
                statusUpdateError: 'Тапсырыс статусын жаңарту қатесі',
                commentSaveError: 'Әкімші пікірін сақтау қатесі',
                createError: 'Тапсырыс жасау қатесі',
                title: 'Басқару панелі',
                manualCreate: 'Тапсырысты қолмен жасау',
                openFormHint: 'Форманы ашу үшін басыңыз',
                products: 'Тауарлар',
                addProduct: '+ Тауар қосу',
                product: 'Тауар',
                selectProduct: 'Тауарды таңдаңыз',
                quantity: 'Саны',
                total: 'Жиыны',
                clientName: 'Клиент аты',
                namePlaceholder: 'Атын енгізіңіз',
                phone: 'Телефон',
                address: 'Жеткізу мекенжайы',
                addressPlaceholder: 'Қала, көше, үй',
                whatsapp: 'WhatsApp арқылы байланысу',
                paymentMethod: 'Төлем тәсілі',
                cash: 'Алғанда қолма-қол',
                card: 'Картаға аудару',
                comment: 'Пікір',
                commentPlaceholder: 'Қосымша ақпарат, клиент тілектері немесе бөлшектер',
                options: 'Нұсқалар / Опциялар',
                optionsPlaceholder: 'JSON немесе мәтін, мысалы: {"size":"160x80","color":"oak"}',
                creating: 'Жасалуда...',
                createOrder: 'Тапсырыс жасау',
                customerOrders: 'Клиент тапсырыстары',
                listHint: 'Клиент пен статус бойынша жылдам іздеу, тізімді қайта жүктемей.',
                searchPlaceholder: 'Аты немесе телефон бойынша іздеу',
                noStatuses: 'Статустар таңдалмаған',
                statusesPrefix: 'Статустар: {{statuses}}',
                filter: 'Сүзгі',
                statuses: 'Статустар',
                reset: 'Қалпына келтіру',
                loading: 'Тапсырыстар жүктелуде...',
                empty: 'Әзірге тапсырыс жоқ.',
                noProducts: 'Тауар жоқ',
                productId: 'Тауар ID: {{id}}',
                payment: 'Төлем',
                open: 'Ашу',
                call: 'Қоңырау шалу',
                cancel: 'Болдырмау',
                modalTitle: 'Тапсырыс #{{id}}',
                goodsWithCount: 'Тауарлар ({{count}} дана)',
                totalAmount: 'Жалпы сома',
                createdAt: 'Құрылған күні',
                updatedAt: 'Жаңартылған күні',
                source: 'Дереккөз',
                customerComment: 'Клиент пікірі',
                adminComment: 'Әкімші пікірі',
                adminCommentPlaceholder: 'Командаға арналған ішкі пікір',
                referenceImages: 'Референс суреттері',
                uploadedByUser: 'Пайдаланушы жүктеген',
                saveComment: 'Пікірді сақтау',
                done: 'Дайын',
                noPhone: 'Телефон жоқ',
            },
        },
    },
    en: {
        common: {
            noPhoto: 'No photo',
            loading: 'Loading...',
            close: 'Close',
            cancel: 'Cancel',
            save: 'Save',
            saving: 'Saving...',
            delete: 'Delete',
            open: 'Open',
            call: 'Call',
            yes: 'Yes',
            no: 'No',
            notSpecified: 'Not specified',
            noDate: 'No date',
            manualOrder: 'Manual order',
            product: 'Product',
            productId: 'Product ID',
            quantity: 'Quantity',
            total: 'Total',
            sum: 'Sum',
            address: 'Address',
            client: 'Client',
            phone: 'Phone',
            status: 'Status',
            comment: 'Comment',
            itemsCount: 'pcs.',
            moreItems: 'and {{count}} more',
        },
        nav: {
            home: 'Home',
            catalog: 'Catalog',
            customOrder: 'Custom Order',
            contacts: 'Contacts',
            cart: 'Cart',
            profile: 'Profile',
            logout: 'Log out',
            login: 'Log in',
            admin: 'Admin',
        },
        home: {
            heroTitle: 'Furniture',
            heroSubtitle: 'With purpose.',
            heroDesc: 'Exceptional design, clean forms and natural materials. We create objects that become part of your life.',
            heroCta: 'View collection',
            featuredTitle: 'Featured',
            featuredAll: 'View all',
            loading: 'Loading catalog...',
            noPhoto: 'No photo',
            ctaTitle: 'Ready to start a project?',
            ctaDesc: 'We will bring your ideas to life with impeccable attention to detail.',
            ctaButton: 'Discuss a project',
            heroAlt: 'Stolyarniy Dvor Kitchen',
        },
        catalog: {
            title: 'Catalog',
            desc: 'Natural solid wood texture, clean lines and handcrafted details. Choose a piece that becomes the centerpiece of your space.',
            empty: 'The catalog is empty or being updated.',
            noPhoto: 'No photo',
            details: 'Details',
        },
        product: {
            backToCatalog: '← Back to catalog',
            notFound: 'Product not found',
            philosophy: 'Product philosophy',
            woodText: 'We handpick every board to preserve its natural grain. Solid wood breathes, lives and grows in character over time. Every cut is unique — that is true luxury.',
            specs: [
                ['Dimensions & configuration', 'Custom dimensions tailored to your needs. Various finish options available.'],
                ['Materials', 'Solid oak, ash or walnut. European oil-wax finish.'],
                ['Production time', 'From 14 to 30 working days depending on complexity.'],
            ],
            orderButton: 'Order a project',
            addToCart: 'Add to cart',
            addedToCart: '✓ Added',
            relatedTitle: 'Related products',
            previousPhoto: 'Previous photo',
            nextPhoto: 'Next photo',
            heritageEyebrow: 'Solid wood heritage',
            heritageTitle: 'Timeless classics',
            relatedHeading: 'Complete your interior',
            relatedText: 'A perfect combination of pieces from the collection.',
            fullCatalog: 'Full catalog',
            ctaTitle: 'Feel the texture.',
            ctaText: 'Visit our showroom to touch the solid wood in person. Or contact us to discuss a custom project.',
            contactsButton: 'Our contacts',
            customOrderButton: 'Custom order',
            decreaseQuantity: 'Decrease quantity',
            increaseQuantity: 'Increase quantity',
        },
        cart: {
            title: 'Cart',
            backToCatalog: 'Catalog',
            summary: 'Summary',
            total: 'Total',
            emptyTitle: 'Cart is empty',
            emptyDesc: 'Add products from the catalog',
            goToCatalog: 'Go to catalog',
            noPhoto: 'No photo',
            orderData: 'Order details',
            name: 'Name',
            phone: 'Phone',
            address: 'Delivery address',
            comment: 'Comment',
            namePlaceholder: 'Your name',
            addressPlaceholder: 'City, street, building',
            commentPlaceholder: 'Order notes',
            errName: 'Name must be at least 2 characters',
            errPhone: 'Enter a valid phone number',
            submitOrder: 'Place order',
            submitting: 'Placing...',
            submitError: 'Failed to place the order. Please try again.',
            successTitle: 'Order placed!',
            successDesc: 'We will contact you shortly.',
            continueShopping: 'Continue shopping',
            goToCart: 'Go to cart',
            unavailableWarning: 'Some products are no longer available',
            removeUnavailable: 'Remove',
            unavailableItem: 'Product unavailable',
            removeItem: 'Remove',
        },
        orderModal: {
            eyebrow: 'Checkout',
            title: 'Review your details and confirm the order',
            product: 'Product',
            selectProduct: 'Select a product',
            quantity: 'Quantity',
            sum: 'Sum',
            addProduct: '+ Add product',
            totalAmount: 'Total amount',
            success: 'Order placed. We will contact you',
            autoClose: 'This window will close automatically.',
            validationSummary: 'Please check the required fields: name, phone and address must be filled in correctly.',
            name: 'Name',
            namePlaceholder: 'John Smith',
            nameHint: 'Please enter a name of at least 2 characters.',
            phone: 'Phone',
            phoneHint: 'Number must be in +7XXXXXXXXXX format.',
            address: 'Delivery address',
            addressPlaceholder: 'City, street, building',
            addressHint: 'Add the full delivery address so we can confirm the order faster.',
            whatsapp: 'Contact via WhatsApp',
            paymentMethod: 'Payment method',
            cash: 'Cash on delivery',
            card: 'Card transfer',
            comment: 'Comment',
            commentPlaceholder: 'Order notes, preferred contact time and wishes',
            cancel: 'Cancel',
            order: 'Place order',
            ordered: 'Order placed',
            processing: 'Processing...',
            close: 'Close',
            errors: {
                name: 'Enter at least 2 characters.',
                nameLetters: 'Only letters and spaces are allowed.',
                phone: 'Enter number in +7XXXXXXXXXX format.',
                address: 'Address must be at least 5 characters.',
                paymentMethod: 'Please select a payment method.',
            },
        },
        customOrder: {
            title: 'Custom',
            subtitle: 'project.',
            desc: 'From sketch to finished piece. Describe your idea, attach references, and we will prepare a quote with all the details.',
            customTitle: 'Custom order',
            steps: [
                { step: '01', title: 'Discussion', text: 'We clarify use cases, dimensions and style.' },
                { step: '02', title: 'Design', text: 'We prepare a detailed drawing and an accurate quote.' },
                { step: '03', title: 'Production', text: 'We select the best solid wood and realise the project.' },
            ],
            stats: [
                { value: '5+', label: 'years of experience' },
                { value: '200+', label: 'pieces made' },
                { value: '100%', label: 'handcrafted' },
            ],
            formTitle: 'Request a quote',
            labelName: 'Name',
            labelPhone: 'Phone',
            labelDetails: 'Project details',
            labelRefs: 'References (up to 5 photos)',
            placeholderName: 'Your name',
            placeholderPhone: '+7 (999) 000-00-00',
            placeholderDetails: 'Describe what you would like to order...',
            uploadText: 'Click or drag photos here',
            uploadHint: 'PNG, JPG up to 5 MB',
            submit: 'Send request',
            submitting: 'Sending...',
            submitted: 'Sent ✓',
            successTitle: 'Request received',
            successDesc: 'We will contact you within an hour to discuss the details.',
            errorAlert: 'Failed to send the request. Please try again later.',
        },
        contacts: {
            title: 'Contact.',
            desc: 'We are always open for a conversation. Ask a question, discuss a project or visit our showroom to touch the solid wood in person.',
            phone: 'Phone',
            schedule: 'Mon–Sun: 09:00 – 19:00',
            whatsapp: 'WhatsApp',
            whatsappLink: 'Message on WhatsApp',
            showroom: 'Showroom',
            address: 'Astana, Barshyn St. 26',
            twoGis: 'Open in 2GIS',
            socials: 'Social media',
            writeUs: 'Write to us',
            mapCaption: 'Astana, Barshyn St. 26',
            mapTitle: 'Showroom on the map',
        },
        footer: {
            tagline: 'A carpentry workshop for serial production and custom orders.',
            contacts: 'Contacts',
            socials: 'Social media',
            navigation: 'Navigation',
            cta: 'Discuss a project',
            rights: '© 2026 Stolyarniy Dvor • All rights reserved',
        },
        auth: {
            tagline: 'Furniture with character and quality',
            login: 'Log in',
            register: 'Sign up',
            namePlaceholder: 'Your name',
            phonePlaceholder: 'Phone (+7...)',
            passwordPlaceholder: 'Password',
            confirmPasswordPlaceholder: 'Confirm password',
            loading: 'Loading...',
            loginButton: 'Log in',
            registerButton: 'Sign up',
            passwordMismatch: 'Passwords do not match',
            connectionError: 'No connection to the server',
        },
        profile: {
            defaultOrderName: 'Order',
            productNumber: 'Product #{{id}}',
            ordersLoadError: 'Error loading orders:',
            editProfile: 'Edit profile',
            myOrders: 'My orders',
            noOrdersTitle: 'You have no orders yet',
            noOrdersDesc: 'You have not ordered anything yet. Go to the catalog to place your first order and refresh your interior.',
            goToCatalog: 'Go to catalog',
            orderTitle: 'Order #{{id}}',
            moreItems: 'and {{count}} more',
            details: 'Details',
            repeat: 'Repeat',
            orderDetails: 'Order details #{{id}}',
            goods: 'Products',
            status: 'Status',
            createdAt: 'Order date',
            amount: 'Amount',
            profileUpdated: 'Profile updated',
            dataSaved: 'Data saved successfully',
            editTitle: 'Edit profile',
            name: 'Name *',
            phone: 'Phone *',
            leavePasswordEmpty: 'Leave blank to keep current password',
            newPassword: 'New password',
            minPasswordPlaceholder: 'At least 6 characters',
            confirmPassword: 'Confirm password',
            repeatPasswordPlaceholder: 'Repeat password',
            save: 'Save',
            saving: 'Saving...',
            loginRequired: 'Please log in to continue.',
            serverError: 'Server error',
            errors: {
                name: 'Name must be at least 2 characters',
                phone: 'Enter a valid phone number',
                password: 'At least 6 characters',
                confirmPassword: 'Passwords do not match',
            },
        },
        statuses: {
            NEW: 'New',
            IN_PROGRESS: 'In progress',
            PROCESS: 'In progress',
            READY: 'Ready',
            DONE: 'Done',
            CANCELLED: 'Cancelled',
        },
        admin: {
            dashboard: {
                title: 'Dashboard',
                loading: 'Loading data...',
                downloadReport: 'Download report',
                allProducts: 'Total products',
                ordersForPeriod: 'Orders for period',
                newOrders: 'New orders',
                forPeriod: 'for period',
                noPreviousData: 'no data for previous period',
                revenue: 'Total revenue',
                avgCheck: 'Average order',
                totalNew: 'Total new',
                chartTitle: 'Order dynamics',
                byMonths: 'by months',
                byDays: 'by days',
                notes: 'Notes',
                notesPlaceholder: 'Write down ideas, numbers or tasks for today...',
                saveNotes: 'Save notes',
                notesSaved: 'Notes saved',
                recentOrders: 'Recent orders',
                noOrders: 'No orders yet.',
                productFallback: 'Product #{{id}}',
                reportTitle: 'ORDERS REPORT',
                reportPeriod: 'Period: {{period}}',
                reportDate: 'Generated: {{date}}',
                sheetOrders: 'Orders',
                sheetSummary: 'Summary',
                sheetByDays: 'By days',
                tableHeaders: ['ID', 'Date', 'Client', 'Phone', 'Address', 'Products', 'Item count', 'Amount (₸)', 'Status'],
                summaryTitle: 'SUMMARY',
                summaryMetric: 'Metric',
                summaryValue: 'Value',
                summaryOrders: 'Total orders',
                summaryRevenue: 'Total revenue (₸)',
                summaryAvg: 'Average order (₸)',
                summaryPopular: 'Most popular product',
                summaryNewOrders: 'Number of new orders',
                pieces: 'pcs.',
                byDaysTitle: 'BY DAYS',
                date: 'Date',
                ordersCount: 'Orders count',
                fileName: 'Orders_report',
                period: 'Period',
                today: 'Today',
                sevenDays: '7 days',
                thirtyDays: '30 days',
                thisMonth: 'This month',
                clickEndDate: 'Click the end date',
            },
            tabs: {
                home: 'Home',
                orders: 'Orders',
                products: 'Products',
            },
            products: {
                title: 'Admin',
                addProduct: 'Add product',
                namePlaceholder: 'Name',
                pricePlaceholder: 'Price',
                descriptionPlaceholder: 'Description',
                uploadImage: 'Upload image',
                uploadLoading: 'Uploading...',
                maxImages: 'Maximum 5 images',
                uploadError: 'Upload error',
                loadError: 'Error loading products',
                addError: 'Error adding product',
                deleteConfirm: 'Delete product?',
                deleteError: 'Error deleting product',
                adding: 'Adding...',
                add: 'Add',
            },
            orders: {
                loadError: 'Error loading data.',
                statusUpdateError: 'Error updating order status',
                commentSaveError: 'Error saving admin comment',
                createError: 'Error creating order',
                title: 'Dashboard',
                manualCreate: 'Create order manually',
                openFormHint: 'Click to open the form',
                products: 'Products',
                addProduct: '+ Add product',
                product: 'Product',
                selectProduct: 'Select a product',
                quantity: 'Quantity',
                total: 'Total',
                clientName: 'Client name',
                namePlaceholder: 'Enter name',
                phone: 'Phone',
                address: 'Delivery address',
                addressPlaceholder: 'City, street, building',
                whatsapp: 'Contact via WhatsApp',
                paymentMethod: 'Payment method',
                cash: 'Cash on delivery',
                card: 'Card transfer',
                comment: 'Comment',
                commentPlaceholder: 'Additional information, client wishes or details',
                options: 'Options / Variants',
                optionsPlaceholder: 'JSON or text, e.g.: {"size":"160x80","color":"oak"}',
                creating: 'Creating...',
                createOrder: 'Create order',
                customerOrders: 'Customer orders',
                listHint: 'Quick search by client and status, without reloading the list.',
                searchPlaceholder: 'Search by name or phone',
                noStatuses: 'No statuses selected',
                statusesPrefix: 'Statuses: {{statuses}}',
                filter: 'Filter',
                statuses: 'Statuses',
                reset: 'Reset',
                loading: 'Loading orders...',
                empty: 'No orders yet.',
                noProducts: 'No products',
                productId: 'Product ID: {{id}}',
                payment: 'Payment',
                open: 'Open',
                call: 'Call',
                cancel: 'Cancel',
                modalTitle: 'Order #{{id}}',
                goodsWithCount: 'Products ({{count}} pcs.)',
                totalAmount: 'Total amount',
                createdAt: 'Created at',
                updatedAt: 'Updated at',
                source: 'Source',
                customerComment: 'Customer comment',
                adminComment: 'Admin comment',
                adminCommentPlaceholder: 'Internal comment for the team',
                referenceImages: 'Reference images',
                uploadedByUser: 'Uploaded by user',
                saveComment: 'Save comment',
                done: 'Done',
                noPhone: 'No phone',
            },
        },
    },
};

export const LANG_NAMES = {
    ru: 'Русский',
    kz: 'Қазақша',
    en: 'English',
};

const LanguageContext = createContext(null);
const SUPPORTED_LANGS = ['ru', 'kz', 'en'];

function getByPath(source, key) {
    return key.split('.').reduce((value, part) => (
        value && Object.prototype.hasOwnProperty.call(value, part) ? value[part] : undefined
    ), source);
}

function interpolate(value, params) {
    if (typeof value !== 'string' || !params) {
        return value;
    }

    return value.replace(/\{\{(\w+)\}\}/g, (_, name) => (
        Object.prototype.hasOwnProperty.call(params, name) ? String(params[name]) : ''
    ));
}

function createTranslator(lang) {
    const current = translations[lang] || translations.ru;

    const translate = (key, params) => {
        const localized = getByPath(current, key);
        const fallback = getByPath(translations.ru, key);
        const value = localized ?? fallback;
        return interpolate(value ?? '', params);
    };

    return Object.assign(translate, current);
}

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(() => {
        const savedLang = localStorage.getItem('lang');
        return SUPPORTED_LANGS.includes(savedLang) ? savedLang : 'ru';
    });

    const switchLang = (newLang) => {
        const nextLang = SUPPORTED_LANGS.includes(newLang) ? newLang : 'ru';
        setLang(nextLang);
        localStorage.setItem('lang', nextLang);
    };

    const t = useMemo(() => createTranslator(lang), [lang]);

    return (
        <LanguageContext.Provider value={{ lang, switchLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLang() {
    const ctx = useContext(LanguageContext);
    if (!ctx) throw new Error('useLang must be used inside LanguageProvider');
    return ctx;
}
